security:
    encoders:
        App\Entity\User:
            algorithm: auto

    providers:
        users:
            entity:
                class: 'App\Entity\User'
                property: 'nickname'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            provider: users

            remember_me:
                secret: '%kernel.secret%'
                always_remember_me: true

            form_login:
                login_path: login
                check_path: login
                username_parameter: nickname
                password_parameter: password
                default_target_path: feed

            logout:
                path: logout

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
